### ISSUE TITLE
Background images deleted in world converted from roll20

### ISSUE THREAD

**Issue by jbom1** [jegasus/world-manager#6]
I attempted to use this tool to compress a Tomb of Annihilation world that was converted from roll20 using KaKaRoTo's converter. However, the background images for nearly every scene were deleted.

The background images are stored in worlds/toa/scenes/backgrounds:
[Files before](https://i.imgur.com/6NCLAqz.png)
[Files after](https://i.imgur.com/VzfHTPn.png)

Here's a sample scene whose background was deleted:
[Scene before](https://i.imgur.com/hTsFcOx.png)
[Scene after](https://i.imgur.com/3iB9xPX.png)
[Console errors after](https://i.imgur.com/Up8zzgJ.png)

After running the command, the command line reported the following:
``Fixed 1361 broken refs by pointing to `worlds` folder instead of `modules` folder.``

The world used to obtain the information above was version 0.1.0 of ToA from the 5etools/Plutonium Foundry world conversions. Prior to running the tool, the world was launched once to raise its system version to dnd5e 0.7.9. Similar results occurred when I ran the tool on my personal ToA world, which was also converted from roll20 using KaKaRoTo's converter. The results were the same regardless of whether "delete unreferenced images" was set to "y" or "n".

OS: Windows 10

**Comment by jegasus** [comment]
Hi there! 
Thanks for reporting this. I'm looking into it right now. When I find what's going on, I'll post an update here. I might need to ask you follow up questions, so keep an eye on this thread.

**Comment by jegasus** [comment]
I've fixed the issue in [release 0.0.2](https://github.com/jegasus/world-manager/releases/tag/0.0.2)! The problem was in the function that fixes image files' extensions (for example, from `PNG` to `JPEG`). 
I'm closing the issue. 
If the problem persists, please feel free to re-open it!
